name: Build Script

on:
    push:
        branches:
            - main
    workflow_dispatch:

jobs:
    build_script:
        name: Build Script
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Cache PNPM modules
              uses: actions/cache@v2
              with:
                  path: ~/.pnpm-store
                  key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-
            - name: Install PNPM
              run: npm i -g pnpm
            - name: Install Packages
              run: pnpm i
            - name: Build
              run: pnpm run build
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN  }}
                  publish_dir: "./dist"
                  user_name: "JacobLinCool"
                  user_email: "jacoblincool@users.noreply.github.com"
                  publish_branch: "dist"
